/**
 * Repeat the previous exercise for a three-dimensional array.
 *
 * Previous exercise:
 * Write a method that creates and initializes a twodimensional array of double. The size of the array is
 * determined by the arguments of the method, and the initialization values are a range determined by beginning
 * and ending values that are also arguments of the method. Create a second method that will print the array
 * generated by the first method. In main( ) test the methods by creating and printing several different sizes of arrays.
 */

public class Ex04_ThreeDimensional {
    static double[][][] createArray(int x, int y, int z, double start, double end) {
        double result[][][] = new double[x][y][z];

        double increment = (end - start) / x * y * z;
        double value = start;

        for (int i = 0; i < result.length; i++)
            for (int j = 0; j < result[i].length; j++)
                for (int k = 0; k < result[i][j].length; k++) {
                result[i][j][k] = value;
                value += increment;
            }

        return result;
    }

    static void printArray(double[][][] array) {
        for(int i = 0; i < array.length; i++) {
            for (int j = 0; j < array[i].length; j++)
                for (int k = 0; k < array[i][j].length; k++)
                System.out.printf("%.2f ", array[i][j][k]);
            System.out.println();
        }
        System.out.println("-------------------");
    }

    public static void main(String[] args) {

        double[][][] arr1 = createArray(3, 4, 3, 0.0, 100.0);
        double[][][] arr2 = createArray(2, 2, 2, 1.1, 9.9);
        double[][][] arr3 = createArray(4, 4, 4, 2.3, 84.6);
        double[][][] arr4 = createArray(3, 3, 3, 0.1, 5.1);

        printArray(arr1);
        printArray(arr2);
        printArray(arr3);
        printArray(arr4);
    }
}
